apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloud-custodian
    version: "1.0"
  name: cloud-custodian
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-custodian
      version: "1.0"
  template:
    metadata:
      labels:
        app: cloud-custodian
        version: "1.0"
    spec:
      containers:
        - env:
            - name: DOTNET_ENVIRONMENT
              value: Production
          image: ghcr.io/hanaim-devops/pitstop-team-luna/cloudcustodian:1.0
          imagePullPolicy: IfNotPresent
          name: auditlogservice
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret